
const types = {
    LIST_USERS: 'LIST_USERS',
    SET_CURRENT_USER: 'SET_CURRENT_USER',
    SET_PAYMENT: 'SET_PAYMENT',
    API_ERRORS: 'API_ERRORS',
    DELETE_USER: 'DELETE_USER'
}

export default types;